### ISSUE TITLE
DOD

### ISSUE THREAD

**Issue by AMHymyilee** [AMHymyilee/cdmx-2018-06-bc-core-am-social-network#23]
- [x] 1. Poner nombre de la app en el inicio de sesión
- [x] 2. Jalar e imprimir el nombre de usuario
     - [x] 2.1 En el muro
 - [x] 3. Arreglar botón de inicio de sesión
 - [x] 4. Editar post
 - [x] 5. Eliminar post
 - [x] 8. Ver perfil

**Comment by soberanesmajo** [comment]
Gracias Adri ✨
